In [1]:
import numpy as np

# Numpy Vectorization

In [2]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5 ])
number = 10

#  number sums up with each array element
result = array1 + number

print(result)

[11 12 13 14 15]


* This is possible because of vectorization.

In [3]:
# define two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[0, 1, 2], [0, 1, 2]])

# add two arrays (vectorization)
array_sum = array1 + array2

print("Sum between two arrays:\n", array_sum)

Sum between two arrays:
 [[1 3 5]
 [4 6 8]]


* This is also a vectorized operation, where corresponding elements of two arrays are added together element-wise.

# Numpy Vectorization Vs Python for Loop

## python for loop

In [13]:
import time

start = time.time()

array1 = [1, 2, 3, 4, 5]

for i in range(len(array1)):
    array1[i] += 10

time.sleep(0.5)
end = time.time()

print("For loop time:", end - start - 0.5)

For loop time: 0.0010902881622314453


## Numpy Vectorization

In [14]:
start = time.time()

array1 = np.array([1, 2, 3, 4, 5 ])

result = array1 + 10

time.sleep(0.5)
end = time.time()

print("Vectorization time:", end - start - 0.5)

Vectorization time: 0.00038433074951171875


# Numpy Vectorize() Function

* ****In NumPy, every mathematical operation with arrays is automatically vectorized.****

In [ ]:
import time

arr = np.array([1, 2, 3, 4, 5])

def add_10(x):
    return x + 10

In [65]:
start = time.time()
vectorized = np.vectorize(add_10)
result = vectorized(arr)
time.sleep(0.5)
end = time.time()

print(result, end - start)

[11 12 13 14 15] 0.5014753341674805


In [66]:
start = time.time()
result = np.array([])
for i in range(len(arr)):
    result = np.append(result, (arr[i] + 10))
result = np.array(result)
time.sleep(0.5)
end = time.time()

print(result, end - start)


[11. 12. 13. 14. 15.] 0.5013911724090576
