In [1]:
import numpy as np

# Creating ndarrays

In [3]:
data1 = [1,2,3,4.5,5,6,7]
arr1 = np.array(data1)
arr1

array([1. , 2. , 3. , 4.5, 5. , 6. , 7. ])

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr1.ndim

1

In [6]:
arr1.shape

(7,)

## zeros, ones, empty, arange

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.empty((2,3,4))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         1.86921007e-306],
        [8.45559303e-307, 7.56593017e-307, 1.95821439e-306,
         1.11260280e-306],
        [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
         1.02359984e-306]],

       [[1.33510679e-306, 2.22522597e-306, 1.33511562e-306,
         6.23055651e-307],
        [7.56599128e-307, 1.24610587e-306, 1.24610723e-306,
         1.42418172e-306],
        [8.06610494e-308, 6.89810244e-307, 1.22387550e-307,
         2.22522596e-306]]])

* `np.empty` will return an array of all zeros. It will return uninitialized garbage values.

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---------------------- 

# Data Types for ndarrays

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4.0,5,6,7,8])
arr1.dtype # int64
arr2.dtype # float64

dtype('float64')

* python un standart **float** türü numpy de `float64` olarak bilinir.

--------

In [ ]:
arr = np.array([1.5,2.2,3.1,4,5])
arr

array([1, 2, 3, 4, 5])

In [20]:
int_arr = arr.astype(np.int64)
int_arr

array([1, 2, 3, 4, 5])

* float dan int türüne `astype` ile çevirirken kayan kısımlar truncated.

# Basic Indexing and Slicing

In [22]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[5]

np.int64(5)

In [ ]:
arr[5:8] # 5.index dahil 8.index dahil degil

array([5, 6, 7])

In [25]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## views and copy

* **arraylerin listelerden bir farkı da** array dilimlemeleri(slices) orjinal array de gösteriliyor(`views`). Kopyalanmıyor. Any **modifications to view** will be reflected in the source array.

In [28]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [ ]:
arr 

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

* `arr_slice` üzerinde yapılan büyün işlemler `arr` üzerinde de gerçekleşti. İşte **view** mantığı bu.

## 2D and 3D arrays

In [31]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr3d = np.array([
    [
        [1,2,3], 
        [4,5,6], 
        [7,8,9], 
        [10,11,12]
    ],
    [
        [13,14,15], 
        [16,17,18], 
        [19,20,21], 
        [22,23,24]
    ]
    ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [34]:
arr3d.shape

(2, 4, 3)

In [35]:
arr3d.ndim

3

In [36]:
arr3d = np.array([
    [[1,2,3],[4,5,6],[7,8,9], [10,11,12]],
    [[13,14,15], [16,17,18], [19,20,21], [22,23,24]]])
arr3d.ndim

3

In [ ]:
arr3d[0][0][1] #2.index

np.int64(2)

In [40]:
for i in range(arr3d.shape[0]):
    for j in range(arr3d.shape[1]):
        for k in range(arr3d.shape[2]):
            print(arr3d[i][j][k])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


## Indexing with slices

In [41]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,0])
arr1d[3:]

array([4, 5, 6, 7, 8, 9, 0])

In [51]:
arr1d[:3]

array([1, 2, 3])

In [45]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2d[1][:2]

array([4, 5])

In [53]:
arr2d[2][1:]

array([8, 9])

---

In [54]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [57]:
arr2d[ : , : 1]

array([[1],
       [4],
       [7]])

# Boolean Indexing