In [2]:
import numpy as np

# Broadcasting : dim compatibility

In [28]:
arr = np.random.rand(4,3)
arr

array([[0.44621157, 0.27235036, 0.25162996],
       [0.41486348, 0.60692285, 0.18568896],
       [0.22675968, 0.8407257 , 0.04523202],
       [0.07144217, 0.8790162 , 0.61657104]])

In [29]:
print(f"sütunların mean'i : {arr.mean(0)}") # each column mean
print(f"satırların mean'i : {arr.mean(1)}") # each row mean

sütunların mean'i : [0.28981922 0.64975378 0.27478049]
satırların mean'i : [0.3233973  0.40249176 0.3709058  0.52234314]


In [ ]:
row_means = arr.mean(1) 
row_means

array([0.3233973 , 0.40249176, 0.3709058 , 0.52234314])

In [31]:
column_means = arr.mean(0)
column_means

array([0.28981922, 0.64975378, 0.27478049])

In [ ]:
arr-row_means # dim uyumsuzluğu arr->(4,3) row_means->(4,0) sebebiyle hata verir.

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [33]:
arr - column_means

array([[ 0.15639234, -0.37740342, -0.02315053],
       [ 0.12504426, -0.04283093, -0.08909153],
       [-0.06305955,  0.19097193, -0.22954848],
       [-0.21837706,  0.22926243,  0.34179054]])

In [35]:
reshaped_row_means = row_means.reshape((4,1))
print(reshaped_row_means)
print(reshaped_row_means - arr)

[[0.3233973 ]
 [0.40249176]
 [0.3709058 ]
 [0.52234314]]
[[-0.12281427  0.05104694  0.07176733]
 [-0.01237172 -0.20443108  0.2168028 ]
 [ 0.14414612 -0.4698199   0.32567378]
 [ 0.45090097 -0.35667307 -0.0942279 ]]


---

## np.newaxis

* boş boyut ekler

In [36]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
print(arr.ndim)
print(arr.shape)

2
(3, 4)


In [48]:
print(arr[:,1])
print(arr[:,1].shape)
print(arr[:,1,np.newaxis])
print(arr[:,1,np.newaxis].shape)
print(arr[:,1,np.newaxis, np.newaxis])
print(arr[:,1,np.newaxis, np.newaxis].shape)
print(arr[np.newaxis,:,1,np.newaxis, np.newaxis])
print(arr[np.newaxis,:,1,np.newaxis, np.newaxis].shape)

[1 5 9]
(3,)
[[1]
 [5]
 [9]]
(3, 1)
[[[1]]

 [[5]]

 [[9]]]
(3, 1, 1)
[[[[1]]

  [[5]]

  [[9]]]]
(1, 3, 1, 1)


### slicing alıştırmaları

In [49]:
arr = np.arange(120).reshape((8,5,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14]],

       [[ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29]],

       [[ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74]],

       [[ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104]],

       [[105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [11

In [55]:
print(arr.ndim)
print(arr.shape)

3
(8, 5, 3)


In [ ]:
# Önden bakış

axis0_1 = arr[np.newaxis,0]
print(axis0_1)
print(axis0_1.shape)
axis0_2 = arr[np.newaxis,1]
print(axis0_2)
print(axis0_2.shape)
axis0_3 = arr[np.newaxis,2]
print(axis0_3)
print(axis0_3.shape)
axis0_4 = arr[np.newaxis,3]
print(axis0_4)
print(axis0_4.shape)
axis0_5 = arr[np.newaxis,4]
print(axis0_5)
print(axis0_5.shape)
axis0_6 = arr[np.newaxis,5]
print(axis0_6)
print(axis0_6.shape)
axis0_7 = arr[np.newaxis,6]
print(axis0_7)
print(axis0_7.shape)
axis0_8 = arr[np.newaxis,7]
print(axis0_8)
print(axis0_8.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]]
(1, 5, 3)
[[[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
(1, 5, 3)
[[[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]
(1, 5, 3)
[[[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]
(1, 5, 3)
[[[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]
(1, 5, 3)
[[[75 76 77]
  [78 79 80]
  [81 82 83]
  [84 85 86]
  [87 88 89]]]
(1, 5, 3)
[[[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]]]
(1, 5, 3)
[[[105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]]]
(1, 5, 3)


In [65]:
# Sağdan Bakış

print(arr[:,:,2].T)
print(arr[:,:,2].T.shape)
print(arr[:,:,2].T.ndim)
print(arr[:,:,1].T)
print(arr[:,:,1].T.shape)
print(arr[:,:,1].T.ndim)
print(arr[:,:,0].T)
print(arr[:,:,0].T.shape)
print(arr[:,:,0].T.ndim)

[[  2  17  32  47  62  77  92 107]
 [  5  20  35  50  65  80  95 110]
 [  8  23  38  53  68  83  98 113]
 [ 11  26  41  56  71  86 101 116]
 [ 14  29  44  59  74  89 104 119]]
(5, 8)
2
[[  1  16  31  46  61  76  91 106]
 [  4  19  34  49  64  79  94 109]
 [  7  22  37  52  67  82  97 112]
 [ 10  25  40  55  70  85 100 115]
 [ 13  28  43  58  73  88 103 118]]
(5, 8)
2
[[  0  15  30  45  60  75  90 105]
 [  3  18  33  48  63  78  93 108]
 [  6  21  36  51  66  81  96 111]
 [  9  24  39  54  69  84  99 114]
 [ 12  27  42  57  72  87 102 117]]
(5, 8)
2


In [ ]:
# Üsstten bakış

print(arr[:,0,:]) #ilk sıra
print(arr[:,1,:]) #ikinci sıra
print(arr[:,2,:]) #3
print(arr[:,3,:]) #4
print(arr[:,4,:]) #5



[[  0   1   2]
 [ 15  16  17]
 [ 30  31  32]
 [ 45  46  47]
 [ 60  61  62]
 [ 75  76  77]
 [ 90  91  92]
 [105 106 107]]
[[  3   4   5]
 [ 18  19  20]
 [ 33  34  35]
 [ 48  49  50]
 [ 63  64  65]
 [ 78  79  80]
 [ 93  94  95]
 [108 109 110]]
[[  6   7   8]
 [ 21  22  23]
 [ 36  37  38]
 [ 51  52  53]
 [ 66  67  68]
 [ 81  82  83]
 [ 96  97  98]
 [111 112 113]]
[[  9  10  11]
 [ 24  25  26]
 [ 39  40  41]
 [ 54  55  56]
 [ 69  70  71]
 [ 84  85  86]
 [ 99 100 101]
 [114 115 116]]
[[ 12  13  14]
 [ 27  28  29]
 [ 42  43  44]
 [ 57  58  59]
 [ 72  73  74]
 [ 87  88  89]
 [102 103 104]
 [117 118 119]]


# np.where()

* `arr = np.where(condition, x, y)`, **condition**: arr'dan seçilecek elemanların koşulu.

**x**: koşul doğruysa eleman yerine döndürülecek değer.

**y**: koşul yanlışsa....

In [70]:
arr = np.array([100,23,61,78,40,250])
arr = np.where(arr>40, 1, 0)
arr

array([1, 0, 1, 1, 0, 1])

In [72]:
arr1 = np.array([100,23,61,78,40,250])
arr2 = np.array([15,24,16,17,18,19])

arr1 = np.where(arr1>40, arr1, arr2)
arr1
# arr1 üzerinde, eğer ilgili eleman 40 dan büyükse arr1 den döndür. değilse arr2 den.

array([100,  24,  61,  78,  18, 250])

# np.broadcast_to

* `np.broadcast_to(array, shape, subok=True/False)`: arrayi istenilen boyuta çekme

In [77]:
arr = np.array([1,2,3,4])
arr = np.broadcast_to(arr, (32,4))
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])