In [1]:
import numpy as np

# Boolen Indexing

In [4]:
arr = np.random.rand(3,3)
arr

array([[0.32047996, 0.55586796, 0.90611861],
       [0.69440431, 0.82752439, 0.57164719],
       [0.45682523, 0.55379912, 0.20875765]])

In [19]:
print(arr[2])
print(arr[2].shape)
print(arr[2:])
print(arr[2:].shape)

[0.45682523 0.55379912 0.20875765]
(3,)
[[0.45682523 0.55379912 0.20875765]]
(1, 3)


In [23]:
print(arr[:,:2])
print(arr[:,:2].shape)

[[0.32047996 0.55586796]
 [0.69440431 0.82752439]
 [0.45682523 0.55379912]]
(3, 2)


In [27]:
print(arr[1,:2])
print(arr[1,:2].shape)

[0.69440431 0.82752439]
(2,)


* `arr[a:b,c:d]` **-->** **:**, *slice* sembolüdür. İfadede **a.satırdan b ye kadar(b dahil değil)** olan satırları dahil tutar. c ve d için de geçerli.

* `arr[a:,:]` **-->** **a. indexe ait olan satırı** ve sonrasını dahil tutar. Virgülden sonrası tüm **sütunlar** dahil.

* `arr[:,:b]` **-->** **b. indexe ait olan sütun hariç** öncesini tutar. Tüm satırlar dahil.

---

In [34]:
names = np.array(['Bob', 'Joe', 'Bob'])

In [35]:
names == 'Bob'

array([ True, False,  True])

In [37]:
arr

array([[0.32047996, 0.55586796, 0.90611861],
       [0.69440431, 0.82752439, 0.57164719],
       [0.45682523, 0.55379912, 0.20875765]])

In [36]:
arr[names == 'Bob']

array([[0.32047996, 0.55586796, 0.90611861],
       [0.45682523, 0.55379912, 0.20875765]])

* ilk satır için `names == 'Bob' ` **true** döndürdüğü için `arr[names == 'Bob']` da ilk satır dahil oldu. **2.satır** için false, haliyle dahil değil. **3** keza ilk satır gibi.

In [38]:
mask = (names == 'Bob') | (names == 'Joe')
mask

array([ True,  True,  True])

In [39]:
arr[mask]

array([[0.32047996, 0.55586796, 0.90611861],
       [0.69440431, 0.82752439, 0.57164719],
       [0.45682523, 0.55379912, 0.20875765]])

In [40]:
arr[~mask]

array([], shape=(0, 3), dtype=float64)

* Bir arrayden **boolen indexing** ile veri çekmek *daima* array'in copy sini oluşturur.

---

In [42]:
data = np.random.randn(4,3)
data

array([[ 1.35201278, -0.24173558,  1.23186734],
       [ 0.64807199,  1.13878047, -1.01436298],
       [ 0.4447134 , -1.20243027, -0.2712965 ],
       [ 1.07522905,  2.95380007,  0.92793054]])

In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])

In [44]:
mask = names == 'Bob'
mask

array([ True, False, False,  True])

In [46]:
data[mask] = 7
data

array([[ 7.        ,  7.        ,  7.        ],
       [ 0.64807199,  1.13878047, -1.01436298],
       [ 0.4447134 , -1.20243027, -0.2712965 ],
       [ 7.        ,  7.        ,  7.        ]])

* names ile bir mask filtresi oluşturdum. Bu mask ı data ya uyguladım. maskın true olduğu kısımlarda filtre uygulandı.

# Fancy Indexing

In [52]:
arr = np.array([10,2,31,17,51,68,7,23])
ind = [1,3,5]

In [53]:
arr[ind]

array([ 2, 17, 68])

In [55]:
data[[0,2],[2,1]]
# array([7, -1.20243027])

array([ 7.        , -1.20243027])

* soldaki **[0,2]** satırları, **[2,1]** ise sütunları belirtir. Mesela, `[0,]-[2,] --> 0.satırın 2.indexdeki elemanı` 

---

In [59]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [62]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

* **1.** sütunun **0. , 3. , 1. ve 2.** elemanını al.

* **5.** sütunun **0. , 3. , 1. ve 2.** elemanını al.

* **7.** sütunun **0. , 3. , 1. ve 2.** elemanını al.

* **2.** sütunun **0. , 3. , 1. ve 2.** elemanını al.